name: nike_store
description: Nike Store
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  intl: ^0.17.0
  json_serializable: ^6.2.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.4
  hive_flutter: ^1.1.0

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/regular.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
